### ISSUE TITLE
Random shots...

### ISSUE THREAD

**Issue by ghost** [the-red-team/XboxOneRapidFire#1]
Random shots still happening...
i ask now in the Arduino forums for a fix...

Edit: I fixed it.
If you're interessted, write me.

**Comment by joint97** [comment]
im new to this, i was wondering how would i wire it up for the xbox controller if i used the attiny 85  code. also how did you fix it

**Comment by justcallmekoko** [comment]
> Random shots still happening...
> i ask now in the Arduino forums for a fix...
> 
> Edit: I fixed it.
> If you're interessted, write me.

@tschagg Not sure what your fix was. This issues was brought to my attention in a youtube comment. I removed a line a while ago for setting a pin state when it was not needed. This corrected the issue and the new code should be available

**Comment by ghost** [comment]
> > Random shots still happening...
> > i ask now in the Arduino forums for a fix...
> > Edit: I fixed it.
> > If you're interessted, write me.
> 
> @tschagg Not sure what your fix was. This issues was brought to my attention in a youtube comment. I removed a line a while ago for setting a pin state when it was not needed. This corrected the issue and the new code should be available

i just modified the script, it wasnt working properly for me, autoshots all the time, and there were useless things in it.
i use now: (fully working, randomshots fixed, tested over hundereds of hours)
**Arduino!**

```
int L3 = A0; int R3 = A1; int RB = A3; int LED = 9;
bool active = false; bool oldOn = false; int buttonState = 0;
void setup() {
  pinMode(L3, INPUT);
  pinMode(RB, INPUT);
  pinMode(R3, INPUT);
  pinMode(LED, OUTPUT);
  Serial.begin(9600);
}
void loop() {
  buttonState = analogRead(RB);
  if (analogRead(L3) < 50 && analogRead(R3) < 50) {
    if (oldOn == false) {
      if (active == false) { active = true; }
      else { active = false; }
      oldOn = true;
      delay(500);
    }
  }
  else { oldOn = false; }
  if (buttonState == HIGH) {
    if (active == true) {
       pinMode(RB, OUTPUT);
       analogWrite(RB, 1000);
       delay(22);
       pinMode(RB, INPUT);
       delay(100);
       }
    }
}
```

**Comment by justcallmekoko** [comment]
Auto-shot issue fixed through pinMode change. Omit analogWrite(RB, 0);

**Comment by razalghul** [comment]
Hello friends, I need your help, when I see this I have doubts, how should the final code be? What part should I eliminate to place this new solution of random shooting?

**Comment by justcallmekoko** [comment]
@razalghul The code change has already been implemented. It should be working find now
